### ISSUE TITLE
[2.4-b05d Forge] Quick fix for the Carried Item config

### ISSUE THREAD

**Issue by ThisOneMadow** [Momo-Studios/Cold-Sweat-Rework-Forge#601]
Not sure if this counts as a bug or (probably 100%) just a change I missed. (I don’t even want to count how many problems I’ve had with the same thing LOL.)

In an older version I used some time ago (v2.3.8), the config worked fine:
https://gist.github.com/ThisOneMadow/1b8b64b3cfc495c779d4359e32a4ca93#file-aetherlantern-json

Everything still works as intended **except** in the newest beta the `"dimension"` part doesn’t seem to work anymore. The config is applying to all dimensions (again).
I tried following the mod’s docs but couldn’t find a way to fix it. I thought maybe the `"entity"` or `"location"` sections aren’t needed anymore, but even after removing or switching a few things around, nothing really worked.

Sorry for bringing up kind of the same issues again, but I’d really appreciate a way to set it up properly so the config can be applied to specific dimensions again. Ty!

**Comment by MikulDev** [comment]
It looks like the "biome", "structure" and "dimension" fields incorrectly expect a list of elements, when they should be looking for just one. For now, you can fix this by making the dimension into a list:
```
"entity": {
    "location": {
      "dimension": [
        "aether:the_aether"
      ]
    }
  }
```
I will have this corrected in the next beta. For the future, though, this field is a [negatable list](https://mikul.gitbook.io/cold-sweat/datapacks/negatable-list), so it can accept one or multiple elements.

**Comment by ThisOneMadow** [comment]
I remember trying that, though even after making it a list didn’t help. It was and still is being applied in every dimension. But if the next update might fix it, I guess I can wait for it!

**Comment by ThisOneMadow** [comment]
The problem still persist after the update :/
List and the single element example doesnt seem to work somehow.
